ufb/models.py
#Application Database Models and Funcations
#Most of these should be self explanitory

from flask.ext.sqlalchemy import SQLAlchemy
from sqlalchemy import *
import pbkdf2

db = SQLAlchemy()

class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,index=True, primary_key=True)
    first = db.Column(db.String(32), nullable=False)
    last = db.Column(db.String(32), nullable=False)
    #Required field for Route Decorators
    nickname = db.Column(db.String(32), nullable=False)
    email = db.Column(db.String(128), unique=True, nullable=False)
    salt = db.Column(db.String(), nullable=False)
    password = db.Column(db.String(), nullable=False)
    created_at = db.Column(db.DateTime, server_default=text('NOW()'), nullable=False)
    #One to many relationship with Posts made by user
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    #Flask Login User Class Required Methods
    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.id)

    def __repr__(self):
        return "<User %r>" % (self.email)

    #Password Methods
    def gen_salt(self):
        self.salt =  pbkdf2.SHA1().hexdigest()

    def hash_pw(self, pw):
        return pbkdf2.crypt(pw, salt=self.salt)

    def set_pw(self, pw):
        self.password = self.hash_pw(pw)

    def validate_pw(self, pw):
        new_hash = self.hash_pw(pw)
        return pbkdf2.HMAC.compare_digest(new_hash, self.password)
        
class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer,index=True, primary_key=True)
    created_at = db.Column(db.DateTime, server_default=text('NOW()'), nullable=False)
    body = db.Column(db.String(256))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    #One to many relationship with Replies to a Post
    replies = db.relationship('Reply', backref='reply', lazy='dynamic')

    def __repr__(self):
        return "<Post %r>" % (self.id)

class Reply(db.Model):
    __tablename__ = 'replies'

    id = db.Column(db.Integer,index=True, primary_key=True)
    created_at = db.Column(db.DateTime, server_default=text('NOW()'), nullable=False)
    body = db.Column(db.String(256))
    #Link Reply back to a user
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    #Link Reply back to a post
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    
    #Return the Author's First and Last for a Reply
    def author(self):
        a = User.query.get(self.user_id)
        return "%s %s" % (a.first, a.last)

    def __repr__(self):
        return "<Post %r>" % (self.id)

ufb/forms.py
#Single File to manage all forms generated via WTF Forms and their validation
#Most of these should be very self explanitory

from flask.ext.wtf import Form
from sqlalchemy.orm.exc import MultipleResultsFound, NoResultFound
from wtforms import fields
from wtforms.validators import Email, InputRequired, ValidationError, Length

from .models import *

class LoginForm(Form):
    email = fields.StringField(validators=[InputRequired(), Email()])
    password =  fields.PasswordField(validators=[InputRequired()])

    def validate_password(form, field):
        try:
            user = User.query.filter(User.email == form.email.data).one()
        except (MultipleResultsFound, NoResultFound):
            raise ValidationError("Invalid user")
        if user is None:
            raise ValidationError("Invalid user")
        if not user.validate_pw(form.password.data):
            raise ValidationError("Invalid password")
        form.user = user

class RegisterForm(Form):
    first = fields.StringField("First Name", validators=[InputRequired()])
    last = fields.StringField("Last Name", validators=[InputRequired()])
    nickname = fields.StringField("Nickname", validators=[InputRequired()])
    email = fields.StringField("Email", validators=[InputRequired()])
    password = fields.PasswordField("Password", validators=[InputRequired()])

    def validate_email(form, field):
        user = User.query.filter(User.email == field.data).first()
        nickname = User.query.filter(User.nickname == field.data).first()
        if user and nickname is not None:
            raise ValidationError("Email is already registered")

#Place Holder for Generating a Profile Form
class ProfileForm(Form):
    pass
    
class PostForm(Form):
    post_body = fields.TextAreaField("Post Something", validators=[Length(min=1, max=254, message="Maximum Length is 254 Characters")])
    #This is to create a individual form submit rather than an entire page
    submit = fields.SubmitField('Submit New Post')

class ReplyForm(Form):
    reply_body = fields.TextAreaField("Reply to Post", validators=[Length(min=1, max=254, message="Maximum Length is 254 Characters")])
    #This is to create a individual form submit rather than an entire page
    submit = fields.SubmitField('Reply to post')

ufb/__init__.py
from flask import Flask
from .models import db
from .views import *
from .authentication import login_manager
import os


#Applicaiton Initialization
app = Flask(__name__)
#Load App Settings based on ENV Var
app.config.from_object(os.environ['APP_SETTINGS'])

#Initialize DB
db.init_app(app)

#Initialize Blueprint for Routes
app.register_blueprint(site)

#Initialize Login Manager from Flask-Login
login_manager.init_app(app)

ufb/views.py
#Single file to isolate all the routes via a Blueprint
#This should be broken out into individual files and Blueprint per function
#Everything currently opperates under the Site Blueprint

from flask import Blueprint, flash, Markup, redirect, render_template, url_for, request
from flask.ext.login import login_required, login_user, logout_user
from jinja2 import TemplateNotFound
from .forms import *
from .models import *

#Regist the Blueprint Object
site = Blueprint('site', __name__, template_folder='templates')

#Redirect all 401 to the login page
#This should be more sophisticated but this works for the state the app is in currently to make sure
#All pages require at least authentication
@site.errorhandler(401)
def four_oh_one(error):
    return redirect(url_for('site.login'))

#IndexPage
@site.route("/")
@login_required
def index():
    users = User.query.all()
    return render_template('index.html', users=users)

#Login Page
@site.route('/login/', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    if form.validate_on_submit():
        login_user(form.user)
        flash("Welcome")
        return redirect(url_for("site.index"))
    return render_template('login.html', form=form)

#Registration Page
@site.route('/register/', methods=('GET', 'POST'))
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User()
        form.populate_obj(user)
        user.gen_salt()
        user.set_pw(user.password)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('site.index'))
    return render_template('register.html', form=form)

#Logout Page
@site.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.login'))

#User Profile Pages (All encompasing at the moment it needs to be broken out and up
@site.route('/profile/<nickname>', methods=('GET', 'POST'))
@login_required
def profile(nickname=None):
    user = User.query.filter(User.nickname == nickname).first()
    posts = Post.query.filter(Post.user_id == user.id).all()
    form = ProfileForm()
    post_form = PostForm()
    reply_form = ReplyForm()
    return render_template('profile.html', user=user, post_form=post_form, reply_form=reply_form, form=form, nickname=nickname, posts=posts)

#Post Submission, uses URL Decorators to pass data back as a URI rather than via an api
@site.route('/submit_post/<int:author_id>/<nickname>', methods=('GET', 'POST'))
@login_required
def submit_post(nickname=None, author_id=None):
    form = PostForm()
    author = User.query.get(author_id)
    if request.method == 'POST':
        if form.validate_on_submit():
            post = Post()
            post.user_id = author_id
            post.body = request.form['post_body']
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('site.profile', nickname=author.nickname))
    return redirect(url_for('site.profile', nickname=author.nickname))

#Reply Submission, uses URL Decorators to pass data back as a URI rather than via an api
@site.route('/sbumit_reply/<int:post_id>/<int:author_id>', methods=('GET', 'POST'))
@login_required
def submit_reply(post_id=None, author_id=None):
    form = ReplyForm()
    post = Post.query.get(post_id)
    post_owner = User.query.get(post.user_id)
    if request.method == 'POST':
        if form.validate_on_submit():
            author = User.query.get(author_id)
            reply = Reply()
            reply.user_id = author.id
            reply.post_id = post.id
            reply.body = request.form['reply_body']
            db.session.add(reply)
            db.session.commit()
            return redirect(url_for('site.profile', nickname=post_owner.nickname))
    return redirect(url_for('site.profile', nickname=post_owner.nickname))

ufb/templates/index.html
{#
Basic Index Page that Lists all users, this should be the meat of where everything lives, but w/o having search this page is just used for listing all the users on the site
#}

{% extends "layout.html" %}

{% block content %}
  {% for u in users %}
    <li>User Profile: <a href="{{url_for('site.profile', nickname=u.nickname)}}">{{u.first}} {{u.last}}</a></li>
  {% endfor %}
{% endblock content %}

ufb/templates/layout.html
<!DOCTYPE html>
{#
This is the defualt layout for all pages, it just contains the basic header information and meta data that can be passed back in other html templates
#}
<html>
<head>
<title>{% block title %}{{ title }}{% endblock %}</title>
</head>
<body>
<header>
<h1>{{ self.title() }}</h1>
<nav>
<ul>
<li><a href="/">Home</a></li>
<li><a href="{{url_for('site.profile', nickname=current_user.nickname)}}">Profile</a></li>
  {% if current_user.is_anonymous() %}
     <li><a href="{{url_for('site.register')}}">Register</a> / <a href="{{url_for('site.login')}}">Log In</a></li>
  {% endif %}
  {% if current_user.is_authenticated() %}
    <li><a href="{{url_for('site.logout')}}">Logout</a></li>
  {% endif %}
</ul>
</nav>
</header>
{% set messages = get_flashed_messages() %}
{% if messages %}
<section>
  {% for message in messages %}
  <p>{{ message }}</p>
  {% endfor %}
</section>
{% endif %}
<section>
{% block content %}{% endblock %}
</section>
<footer>
</footer>
</body>
</html>

ufb/templates/login.html
{#
Basic Login Page
#}

{% extends "layout.html" %}
{% import "helpers/forms.html" as forms %}
{% block title %}Log into UFB!{% endblock %}
{% block content %}
{{super()}}
<form action="{{ url_for('site.login', ext=request.args.get('next', '')) }}" method="POST">
{{ forms.render(form) }}
<p><input type="Submit" value="Sign In"></p>
</form>
{% endblock content %}

ufb/templates/profile.html
{#
Basic Profile Page, This was baiscally used to develop the Posts and Replies and all general data pertaining to a user
#}

{% extends "layout.html" %}

{# 
Load the form helper templates
Uses general forms helper for the profie 
Uses specific forms helpers for posts and replies
#}
{% import "helpers/forms.html" as forms %}
{% import "helpers/post_form.html" as post_forms %}
{% import "helpers/reply_form.html" as reply_forms %}

{% block title %}Welcome to {{user.first}} {{user.last}} UFB's Profile!{% endblock %}
{% block content %}
{{super()}}

{# Load all the form templates into the body #}

  <form action="{{ url_for('site.submit_post', ext=request.args.get('next', ''), author_id=current_user.id, nickname=current_user.nickname) }}" method="POST">
  {{ post_forms.render(post_form) }}
  </form>
<h3>Posts</h3>
{% for p in posts %}
  <li>
    {{p.body}}
    {% for r in p.replies %}
      <dd>
      <li>{{r.author()}}: {{r.body}}</li>
      </dd>
    {% endfor %}
    <form action="{{ url_for('site.submit_reply', ext=request.args.get('next', ''), post_id=p.id, author_id=current_user.id) }}" method="POST">
    {{ reply_forms.render(reply_form) }}
    </form>
  </li>
{% endfor %}
{% endblock content %}

ufb/templates/register.html
{#
General user Registration Page
#}

{% extends "layout.html" %}

{# Load Generic Form Helpers #}
{% import "helpers/forms.html" as forms %}

{% block title %}Regester for UFB!{% endblock %}
{% block content %}
{{super()}}
<form action="{{ url_for('site.register', ext=request.args.get('next', 'author_id', 'nickname')) }}" method="POST">
{{ forms.render(form) }}
<p><input type="Submit" value="Register Here"></p>
</form>
{% endblock content %}